name: Walkathon Check-in Bot

on:
  push:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run check-in bot
        env:
          WALKATHONPASSSYSTEM: ${{ secrets.WALKATHONPASSSYSTEM }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          python checkin_bot.py
