name: Walkathon Check-In Bot

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:       # Allows manual trigger from GitHub UI

concurrency:
  group: walkathon-checkin-bot
  cancel-in-progress: true  # Ensures only one active instance

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 125  # Kill if stuck after 2 hours and 5 minutes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write service credentials to file
        env:
          WALKATHONPASSSYSTEM: ${{ secrets.WALKATHONPASSSYSTEM }}
        run: |
          echo "$WALKATHONPASSSYSTEM" > walkathon-creds.json

      - name: Run Walkathon Check-In Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          WALKATHONPASSSYSTEM: ${{ vars.WALKATHONPASSSYSTEM }}
        run: |
          python checkin_bot.py
